// Generated by Lasy AI - https://lasy.ai
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wippel Arquitetura & Engenharia",
  description: "Sistema de gestão de obras e clientes da Wippel Arquitetura & Engenharia",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Wippel App",
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: [
      {
        url: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/b926537c-4ac1-40b9-90f2-a4a516b8859a.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        url: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/1068efad-9fa4-4819-a205-9feef69d4a31.png",
        sizes: "512x512",
        type: "image/png",
      },
    ],
    apple: [
      {
        url: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/b926537c-4ac1-40b9-90f2-a4a516b8859a.png",
        sizes: "192x192",
        type: "image/png",
      },
    ],
  },
};

export const viewport: Viewport = {
  themeColor: "#C02C33",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Wippel App" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-TileColor" content="#C02C33" />
        <meta name="msapplication-tap-highlight" content="no" />
        <link rel="apple-touch-icon" href="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/b926537c-4ac1-40b9-90f2-a4a516b8859a.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/b926537c-4ac1-40b9-90f2-a4a516b8859a.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/1068efad-9fa4-4819-a205-9feef69d4a31.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Script
          id="register-sw"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                  navigator.serviceWorker.register('/sw.js')
                    .then(function(registration) {
                      console.log('SW registered: ', registration);
                    })
                    .catch(function(registrationError) {
                      console.log('SW registration failed: ', registrationError);
                    });
                });
              }
            `,
          }}
        />
      </body>
    </html>
  );
}